services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: simple_balance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d simple_balance"]
      interval: 2s
      timeout: 3s
      retries: 20
    volumes:
      - dev-postgres:/var/lib/postgresql/data

volumes:
  dev-postgres:
