import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { MAX_FREE_ACCOUNTS, PLAN_LABELS, plans } from "../src/shared/domain.js";
import { APP_NAME, APP_VERSION } from "../src/shared/version.js";

/**
 * `docs/product/facts.json`, the contract the marketing site consumes.
 *
 * That site is a separate repository making claims about this one, and it
 * cannot read TypeScript. Before this file the only mechanism was somebody
 * remembering, and it had already failed once: this application displayed
 * "Plus" while the site said "Premium".
 *
 * The file is generated. This test **compares** rather than regenerating,
 * because a check that rewrites the thing it is checking is not a check —
 * a stale file has to fail, not be quietly fixed by the suite.
 */
const facts = JSON.parse(readFileSync(join(process.cwd(), "docs/product/facts.json"), "utf8")) as {
  derived: {
    appName: string;
    appVersion: string;
    planKeys: string[];
    plans: Record<string, { label: string; accountLimit: number | null; advertising: boolean }>;
  };
  declared: {
    prices: { currency: string; monthly: string; yearly: string };
    capabilities: string[];
    paidPlanAdds: string[];
  };
};

describe("the published product facts", () => {
  it("names the application and the version the source does", () => {
    expect(facts.derived.appName).toBe(APP_NAME);
    expect(facts.derived.appVersion).toBe(APP_VERSION);
  });

  it("carries every plan the enum declares, and no other", () => {
    // A plan added to `plans` and not here would be a plan the marketing
    // site never hears about.
    expect(facts.derived.planKeys).toEqual([...plans]);
    expect(Object.keys(facts.derived.plans).sort()).toEqual([...plans].sort());
  });

  it("states the free account limit the ledger actually enforces", () => {
    // The number the whole pricing page rests on.
    expect(facts.derived.plans.free?.accountLimit).toBe(MAX_FREE_ACCOUNTS);
  });

  it("gives the paid plan no limit rather than a large one", () => {
    // Null, because a number here is a number somebody eventually prints.
    expect(facts.derived.plans.plus?.accountLimit).toBeNull();
  });

  it("uses the labels a person reads, not the wire values", () => {
    expect(facts.derived.plans.free?.label).toBe(PLAN_LABELS.free);
    expect(facts.derived.plans.plus?.label).toBe(PLAN_LABELS.plus);
    // And the two are genuinely different, which is the whole reason the
    // labels exist separately from the keys.
    expect(PLAN_LABELS.plus).not.toBe("plus");
  });

  it("says which plan sees advertising", () => {
    // `getAdPlacement` returns null for anybody not on the free plan, so
    // this is the free plan and nothing else.
    expect(facts.derived.plans.free?.advertising).toBe(true);
    expect(facts.derived.plans.plus?.advertising).toBe(false);
  });

  it("declares prices as decimal strings, never as numbers", () => {
    // `AGENTS.md`: money is never a JavaScript float. A price in this file is
    // money somebody will render, so it is a string here too.
    for (const value of [facts.declared.prices.monthly, facts.declared.prices.yearly]) {
      expect(typeof value).toBe("string");
      expect(value).toMatch(/^\d+\.\d{2}$/);
    }
    expect(facts.declared.prices.currency).toMatch(/^[A-Z]{3}$/);
  });

  it("lists what the paid plan adds, and it is only the two things", () => {
    // The product's position: Premium raises a limit and removes ads. A
    // third entry here is a capability held back from the free plan, which
    // is a different product.
    expect(facts.declared.paidPlanAdds).toHaveLength(2);
  });

  it("describes capabilities as one list, because both plans have all of them", () => {
    expect(facts.declared.capabilities.length).toBeGreaterThan(10);
    for (const capability of facts.declared.capabilities) {
      expect(capability.length, `"${capability}" is too short to mean anything`).toBeGreaterThan(
        15,
      );
    }
  });

  it("marks itself generated, so nobody edits it by hand", () => {
    expect(JSON.stringify(facts)).toContain("Generated by scripts/build-product-facts.mjs");
  });
});
