import { readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { BILLING_GRACE_DAYS, MAX_FREE_ACCOUNTS, PLAN_LABELS, plans } from "../src/shared/domain.js";
import { APP_NAME, APP_VERSION } from "../src/shared/version.js";

/**
 * `docs/product/facts.json`, the contract the marketing site consumes.
 *
 * That site is a separate repository making claims about this one, and it
 * cannot read TypeScript. Before this file the only mechanism was somebody
 * remembering, and it had already failed once: this application displayed
 * "Plus" while the site said "Premium".
 *
 * The file is generated. This test **compares** rather than regenerating,
 * because a check that rewrites the thing it is checking is not a check —
 * a stale file has to fail, not be quietly fixed by the suite.
 */
const facts = JSON.parse(readFileSync(join(process.cwd(), "docs/product/facts.json"), "utf8")) as {
  derived: {
    appName: string;
    appVersion: string;
    planKeys: string[];
    plans: Record<string, { label: string; accountLimit: number | null; advertising: boolean }>;
  };
  declared: {
    prices: { currency: string; monthly: string; yearly: string };
    capabilities: string[];
    paidPlanAdds: string[];
  };
};

describe("the published product facts", () => {
  it("names the application and the version the source does", () => {
    expect(facts.derived.appName).toBe(APP_NAME);
    expect(facts.derived.appVersion).toBe(APP_VERSION);
  });

  it("carries every plan the enum declares, and no other", () => {
    // A plan added to `plans` and not here would be a plan the marketing
    // site never hears about.
    expect(facts.derived.planKeys).toEqual([...plans]);
    expect(Object.keys(facts.derived.plans).sort()).toEqual([...plans].sort());
  });

  it("states the free account limit the ledger actually enforces", () => {
    // The number the whole pricing page rests on.
    expect(facts.derived.plans.free?.accountLimit).toBe(MAX_FREE_ACCOUNTS);
  });

  it("gives the paid plan no limit rather than a large one", () => {
    // Null, because a number here is a number somebody eventually prints.
    expect(facts.derived.plans.plus?.accountLimit).toBeNull();
  });

  it("uses the labels a person reads, not the wire values", () => {
    expect(facts.derived.plans.free?.label).toBe(PLAN_LABELS.free);
    expect(facts.derived.plans.plus?.label).toBe(PLAN_LABELS.plus);
    // And the two are genuinely different, which is the whole reason the
    // labels exist separately from the keys.
    expect(PLAN_LABELS.plus).not.toBe("plus");
  });

  it("says which plan sees advertising", () => {
    // `getAdPlacement` returns null for anybody not on the free plan, so
    // this is the free plan and nothing else.
    expect(facts.derived.plans.free?.advertising).toBe(true);
    expect(facts.derived.plans.plus?.advertising).toBe(false);
  });

  it("declares prices as decimal strings, never as numbers", () => {
    // `AGENTS.md`: money is never a JavaScript float. A price in this file is
    // money somebody will render, so it is a string here too.
    for (const value of [facts.declared.prices.monthly, facts.declared.prices.yearly]) {
      expect(typeof value).toBe("string");
      expect(value).toMatch(/^\d+\.\d{2}$/);
    }
    expect(facts.declared.prices.currency).toMatch(/^[A-Z]{3}$/);
  });

  it("lists what the paid plan adds, and it is only the two things", () => {
    // The product's position: Premium raises a limit and removes ads. A
    // third entry here is a capability held back from the free plan, which
    // is a different product.
    expect(facts.declared.paidPlanAdds).toHaveLength(2);
  });

  it("describes capabilities as one list, because both plans have all of them", () => {
    expect(facts.declared.capabilities.length).toBeGreaterThan(10);
    for (const capability of facts.declared.capabilities) {
      expect(capability.length, `"${capability}" is too short to mean anything`).toBeGreaterThan(
        15,
      );
    }
  });

  it("marks itself generated, so nobody edits it by hand", () => {
    expect(JSON.stringify(facts)).toContain("Generated by scripts/build-product-facts.mjs");
  });

  it("is exactly what its builder writes, key for key", async () => {
    // The checks above hold the fields somebody thought to name, and a key
    // nobody named goes unseen: the builder could drop one while the committed
    // file kept it, and the site would go on reading it. Comparing with the
    // builder's output is still a comparison — importing it writes nothing —
    // so a stale file fails here rather than being regenerated.
    //
    // Imported by URL because the builder is plain ESM with no declaration
    // file, and the one thing read from it is typed right here: an object the
    // committed JSON has to equal, which is nothing an `any` could make vacuous.
    const builder = new URL("../scripts/build-product-facts.mjs", import.meta.url).href;
    const { buildProductFacts } = (await import(builder)) as { buildProductFacts: () => unknown };
    expect(facts).toEqual(JSON.parse(JSON.stringify(buildProductFacts())));
  });

  it("names no schema, because nobody serves one", () => {
    // `https://smpl.money/schemas/product-facts.json` is an address neither
    // repository publishes, so an editor or a validator that follows a
    // `$schema` naming it gets the site's 404 page. The key belongs in the
    // change that publishes the schema, and not before.
    expect(Object.keys(facts)).not.toContain("$schema");
  });
});

/**
 * The same facts, where a person using the product reads them.
 *
 * `docs/guide.md` explains the plans to somebody on a deployment that sells
 * them, and it has to name the plans and the free limit in words. Those are
 * exactly the claims this file publishes, and a guide still giving the old
 * number after a change to `MAX_FREE_ACCOUNTS` would be the failure that made
 * this file necessary — two places, one of them remembered. So the guide's
 * Plans section is held to the facts rather than to a number typed here. The
 * one number it states that the facts do not carry, how long a failed renewal
 * keeps Premium, is held to `BILLING_GRACE_DAYS` for the same reason: the Plan
 * page's alert said "a few days" while that went from seven to fifteen.
 */
describe("the guide's account of the plans", () => {
  const guide = readFileSync(join(process.cwd(), "docs/guide.md"), "utf8");
  // Prose is wrapped at eighty columns, so a phrase can break anywhere; the
  // section is compared with its line breaks read as the spaces they are.
  const plansSection = (
    guide.split(/^## /m).find((section) => section.startsWith("Plans\n")) ?? ""
  ).replace(/\s+/g, " ");
  // To twenty because the grace is fifteen. A number past the end of this has
  // no word to be held by, and the two tests that need one fail and say so.
  const inWords = [
    "zero",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "fifteen",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty",
  ];
  const count = (pattern: string) =>
    (plansSection.match(new RegExp(`\\b${pattern}\\b`, "gi")) ?? []).length;

  it("has a Plans section, listed in its contents", () => {
    expect(plansSection, "docs/guide.md has no `## Plans` section").not.toBe("");
    expect(guide).toContain("- [Plans](#plans)");
  });

  it("calls each plan by the label a person reads", () => {
    for (const key of facts.derived.planKeys) {
      const label = facts.derived.plans[key]?.label ?? "";
      expect(plansSection, `the guide never names ${label}`).toContain(`**${label}**`);
    }
  });

  it("states the free limit the ledger enforces", () => {
    const limit = facts.derived.plans.free?.accountLimit ?? -1;
    const word = inWords[limit];
    expect(word, `no word for a limit of ${limit}; extend the list`).toBeDefined();
    expect(plansSection).toContain(`keeps ${word} accounts usable`);
  });

  it("states how long a failed renewal keeps Premium", () => {
    const word = inWords[BILLING_GRACE_DAYS];
    expect(
      word,
      `no word for a grace of ${BILLING_GRACE_DAYS} days; extend the list`,
    ).toBeDefined();
    expect(plansSection).toContain(`Premium continues for ${word} days`);
  });

  it("writes no number there but the limit, the plan count and the grace", () => {
    // The section states the limit four times, and holding only the phrase
    // above would pass a guide that changed one of them and left the rest. So
    // every number word in it, up to twenty, is the limit, the count of plans
    // once, or the grace as a count of days. "One" is left out because the
    // section uses it as a pronoun ("delete one").
    const limit = facts.derived.plans.free?.accountLimit ?? -1;
    const planCount = facts.derived.planKeys.length;
    expect(plansSection).toContain(`There are ${inWords[planCount]} plans`);
    for (const [value, word] of inWords.entries()) {
      if (value === limit || word === "one") continue;
      const found = count(word);
      // Every mention of the grace's word has to be that many days, so
      // "fifteen accounts" fails here as surely as "sixteen days" does.
      const allowed =
        (value === planCount ? 1 : 0) + (value === BILLING_GRACE_DAYS ? count(`${word} days`) : 0);
      expect(
        found,
        `the Plans section says "${word}"; the limit is ${limit}, the grace ${BILLING_GRACE_DAYS} days`,
      ).toBe(allowed);
    }
  });
});
